.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. dankcoin_qt test_dankcoin_qt
clean: FORCE
	$(MAKE) -C .. dankcoin_qt_clean test_dankcoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_dankcoin_qt_check
dankcoin-qt dankcoin-qt.exe: FORCE
	 $(MAKE) -C .. dankcoin_qt
